CREATE MATERIALIZED VIEW user_and_comments
  BUILD IMMEDIATE
  REFRESH ON COMMIT
  AS
  SELECT C.USER_ID,U.USERNAME,U.FULL_NAME,U.GENDER,C.ID,C.COMMENTSTRING FROM USERS U ,COMMENTS C WHERE U.ID = C.USER_ID;

EXPLAIN PLAN FOR
SELECT C.USER_ID,U.USERNAME,U.FULL_NAME,U.GENDER,C.ID,C.COMMENTSTRING FROM USERS U ,COMMENTS C WHERE U.ID = C.USER_ID;

EXPLAIN PLAN FOR
select * from user_and_comments;

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());
alter session set query_rewrite_enabled = true ;

select * from V$option;

SELECT * FROM v$option WHERE LOWER(parameter) LIKE '%aterialized%';
